# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

# Tell Travis CI we are using PHP
language: php

# The platforms you wants to test on
os:
  - linux
  
# git configs
git:
  depth: 1

# Define the php versions against we want to test our code
php:
    - 7.0


matrix:
  fast_finish: true


# We don't want to run linux commands as super user
sudo: false

# Note: Code coverage requires php Xdebug extension  to enabled

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - composer install --no-interaction
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

# Create a storage folder for Coverage report
before_script:
    - mkdir -p build/logs
    - ls -al

# Testing the app (see phpunit.xml), generating Code Coverage report
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml


#after_script:

# Submit generated coverage report to Coveralls servers, see .coveralls.yml
# Submit generated coverage report to codecov.io
after_success:
 - travis_retry php coveralls.phar -v
 - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Tell Travis CI to monitor only 'master' and 'develop' branch
branches:
  only: 
    - master
	- develop

# Configure email notifications
notifications:
     email:
        on_success: never
        on_failure: always

# You can delete cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer
